### ISSUE TITLE
Add an LRU cache for blockstore (and in the future, datastore)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-repo#110]

**Comment by Kubuxu** [comment]
In go-ipfs we decided against it after benchmarks, the system level fs cache was enough, but it would be better if you test it for yourself as the situation might be different.

**Comment by diasdavid** [comment]
Interesting, in JS might be different. Another consideration is that for 'stores' that are networked (i.e: S3), LRU will be very useful.

Thanks @Kubuxu :)
