### ISSUE TITLE
ipfs-repo.next()

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-repo#112]
> Notes from the discussion with @dignifiedquire, @VictorBjelkholm, @Kubuxu and @whyrusleeping. 

We will be moving out of `pull-blob-store` and just use js-datastore. js-datastore differs from blob-store on its ability to run queries.

- [x] Implement js-datastore-fs
- [x] Implement js-datastore-level-db
- [x] Implement js-datastore-indexed-db (browser)
- [x] Drop streaming interface at the repo level (not used, all the control flow is actually done in the layers above, which is more power for the user), this will reduce pull-stream creeping.
- [x] Migrate repo.blockstore to use js-datastore-fs in Node.js and js-datastore-indexed-db in the browser
- [x] Implement repo.datastore and use js-datastore-fs in Node.js and js-datastore-indexed-db in the browser
- [ ] Since we are at it, update the spec https://github.com/ipfs/specs/tree/master/repo

**Comment by dignifiedquire** [comment]
> Drop streaming interface at the repo level (not used, all the control flow is actually done in the layers above, which is more power for the user), this will reduce pull-stream creeping.

This means we should figure out the batch interface to do multi delete and puts.

**Comment by Kubuxu** [comment]
You will probably need `js-datastore-mount` for combining the fs and level-db datastores into one datastore.

**Comment by diasdavid** [comment]
@Kubuxu we've support for multiple drivers already, thanks for bringing that up :)

**Comment by SidHarder** [comment]
@diasdavid I finished implementing js-level-pull-blob-store and was planning to go back to work on  js-ipfs-repo/datastore.  Does it make sense for me to keep working on this in light of this issue? I would be happy to help with this effort if it makes sense.

**Comment by SidHarder** [comment]
@diasdavid  Does the js-datastore spec exist somewhere, I'm not finding it.

**Comment by diasdavid** [comment]
js-datastore is essentially a blob-store + a key/query API, so yes, all the work on js-level-pull-blob-store will be used, thank you for getting that done :)

The datastore work is available here: https://github.com/datastore
With a 'pre' (really old) version of what the datastore for JS is: https://github.com/jbenet/node-datastore

Going to ask @jbenet to get access to that org and get all the repos in one place.

**Comment by diasdavid** [comment]
good news, managed to get https://github.com/diasdavid/js-datastore from @jbenet :)

**Comment by dignifiedquire** [comment]
I think this would be a great starting point for testing out types in Javascript, so that we can define some nice interfaces.

**Comment by diasdavid** [comment]
@dignifiedquire started experimenting with it at https://github.com/dignifiedquire/js-datastore

**Comment by dignifiedquire** [comment]
TODO: Investigate level-down and level-up interfaces if there is something we can reuse
