### ISSUE TITLE
Broken on Windows since interface-datastore use of os-specific path separators

### ISSUE THREAD

**Issue by Expyron** [ipfs/js-ipfs-repo#144]
In commit [d7ec65a](https://github.com/ipfs/interface-datastore/commit/d7ec65a), interface-datastore was changed to use os-specific path separators.

However, js-ipfs-repo is still hardcoded to use a slash ([here](https://github.com/ipfs/js-ipfs-repo/blob/master/src/blockstore.js#L20), maybe other places). This throws an error [here](https://github.com/ipfs/interface-datastore/blob/master/src/key.js#L45).

The specifications of interface-datastore should be clarified as to whether we should always use slashes or os-specific path separators, and either interface-datastore or js-ipfs-repo fixed in accordance with the specifications.

I can submit a pull-request depending on the decision.

**Comment by diasdavid** [comment]
Ref: https://github.com/ipfs/js-ipfs/issues/1017

**Comment by Expyron** [comment]
After some more checking, while this is easy to fix for the blockstore by simply normalizing the path, there is also the same issue in the datastore.

A datastore created on Windows will contain keys with backslashes. This means datastores created on Linux cannot be read on Windows, and conversely. Interop tests are failing on Windows because the test repo has (obviously) been created with slashes.

**Comment by richardschneider** [comment]
The datastore **should** be os-agnostic.  All keys should use the same path separator of `/`.  Only file storage implementations should worry about the os styled path conventions.

@pvh has raised https://github.com/ipfs/interface-datastore/pull/11 which is a step in the correct direction.

**Comment by richardschneider** [comment]
I'm getting the following error when running the **tests** on windows


```
 1) IPFS Repo Tests on on Node.js default "before all" hook:
: The filename, directory name, or volume label syntax is incorrect.s-ipfs-repo\test\test-repo-for-1509616898591\datastore/MANIFEST-000052

      at c:\Users\Owner\Documents\GitHub\js-ipfs-repo\node_modules\levelup\lib\levelup.js:117:34
      at c:\Users\Owner\Documents\GitHub\js-ipfs-repo\node_modules\leveldown\node_modules\abstract-leveldown\abstract-leveldown.js:39:16
```

Looks like levelup needs some TLC for windows.

**Comment by diasdavid** [comment]
Let's see how it behaves with the new datastores! => Track here: https://github.com/ipfs/js-ipfs-repo/pull/146/
