### ISSUE TITLE
Does not work in Firefox?

### ISSUE THREAD

**Issue by spaceywolfi** [ipfs/js-ipfs-repo#145]
OpenError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.

it works fine on chrome
can anyone reproduce this error?
i used the basic start code:
```javascript
const IPFSRepo = require('ipfs-repo')
const repo = new IPFSRepo('/tmp/ipfs-repo')

repo.init({ cool: 'config' }, (err) => {
  if (err) {
    throw err
  }

  repo.open((err) => {
    if (err) {
      throw err
    }

    console.log('repo is ready')
  })
})
```

**Comment by diasdavid** [comment]
@spaceywolfi mind submitting a test with this case? We run tests in Firefox and Chrome on CI, it should get caught.

**Comment by spaceywolfi** [comment]
@diasdavid  sure emm, sorry for being a newb, how can i run a test with this case?

**Comment by spaceywolfi** [comment]
i am using the quasar framework, i just set up a simple project to demonstrate the problem. 

```
npm install -g quasar-cli
git clone https://gitlab.com/spaceywolfi/ipfs-test.git
cd ipfs-test
quasar dev
```
in chrome i get the message 'repo ready'
in firefox i get the error that i mentioned before

**Comment by diasdavid** [comment]
@spaceywolfi did you happen to open your happen in incognito:

**Comment by diasdavid** [comment]
Closing as there was no follow up

**Comment by spaceywolfi** [comment]
@diasdavid sorry for not responding earlier :/
i changed my approach and i am not longer using quasar, i do not know if this problem still exists so thank you for closing it.

**Comment by DiThi** [comment]
I have this problem as well. Firefox 58 and 59b6. Not in incognito. Tried in several profiles and enabling the flag "dom.indexedDB.experimental" just in case.
