### ISSUE TITLE
Jenkins windows error

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs-repo#150]
@VictorBjelkholm wrote:

> Did some testing with this for the new CI setup, and got this error:
>
>![image](https://user-images.githubusercontent.com/459764/32573761-0caff7f6-c49d-11e7-9ca1-a08e865e0c46.png)
>
>Was running from commit `9b8c3ba3544281ca84f611e3eecd08fce3e9f3dd`

**Comment by richardschneider** [comment]
@VictorBjelkholm Are you sure you are building from `master`?

It;s working on circle, travis and appveyor.  See https://github.com/ipfs/js-ipfs-repo/pull/151

**Comment by VictorBjelkholm** [comment]
@richardschneider I used commit `9b8c3ba3544281ca84f611e3eecd08fce3e9f3dd` which seems to be the latest commit on `master` https://github.com/ipfs/js-ipfs-repo/commits/master

**Comment by richardschneider** [comment]
@VictorBjelkholm Is there a PR or branch that I can view?

**Comment by richardschneider** [comment]
@VictorBjelkholm any progress on this?

**Comment by VictorBjelkholm** [comment]
Still no luck, was thinking the path was too long but seems OK. You can see the build output here: http://165.227.71.94:8090/blue/organizations/jenkins/js-ipfs-repo/detail/master/7/pipeline

Same commit is passing on https://ci.appveyor.com/project/diasdavid/js-ipfs-repo/build/37/job/5s4754tua3a41wcm

Jobs run via https://wiki.jenkins.io/display/JENKINS/Swarm+Plugin and via jenkins worker (a java application), was thinking that messed with the paths somehow but running `npm test` manually via the GUI on a windows host shows the same issue...

Have we verified windows compat outside of appveyor?

**Comment by richardschneider** [comment]
> Have we verified windows compat outside of appveyor?

Just on my laptop

**Comment by richardschneider** [comment]
FYI, here's the  build on my laptop [js-ipfs-repo.build.txt](https://github.com/ipfs/js-ipfs-repo/files/1465769/js-ipfs-repo.build.txt)

**Comment by VictorBjelkholm** [comment]
I've now tested this on a Windows 10 Home VM as well, and getting the same error (without involving jenkins at all).

Could you try to install dependencies from scratch? Maybe you have some module linked still whose changes hasn't been deployed?

**Comment by richardschneider** [comment]
Attached is the log from a scratch build.  Could you send me yours?

[scratch-build.txt](https://github.com/ipfs/js-ipfs-repo/files/1472227/scratch-build.txt)

**Comment by VictorBjelkholm** [comment]
Let's continue here: https://github.com/ipfs/js-ipfs-repo/pull/153
