### ISSUE TITLE
Version up breaks many tests in other packages

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs-repo#152]
Other packages that use a IPFS repo in a test fixture, for example [js-ipfs-bitswap](https://github.com/ipfs/js-ipfs-bitswap), now break with the [commit](https://github.com/ipfs/js-ipfs-repo/commit/27553a3d51ef5b2c98a21efb67e5fc12c4a8deb1) and generate the following error

```
Error: version mismatch: expected v6, found v5
      at get (node_modules\ipfs-repo\src\version.js:57:27)
      at store.get (node_modules\ipfs-repo\src\version.js:31:9)
      at node_modules\graceful-fs\graceful-fs.js:78:16
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:513:3)
```

The issue is the version number.  The repo in a test fixture has a version number of 5.  But this new code requires version 6.  **Why?** 

If there is a real difference between 5 and 6, then the package should gracefully upgrade the database.

**Comment by richardschneider** [comment]
I have go-ipfs version 0.4.7 installed on my machine,  When I run js-ipfs, via `node src/cli/bin.js` I get the version mismatch error.

So this means that js-ipfs is **NOT** interop with go-ipfs!

**Comment by richardschneider** [comment]
Perhaps the version number check can just be removed.

**Comment by diasdavid** [comment]
Answered here https://github.com/ipfs/js-ipfs-bitswap/pull/154#issuecomment-343416012

This needs to be solved by writing the spec and implementing compliance tests. Until then, we are in this weird situation.

Just to make sure that no wrong claims are broadcasted. **js-ipfs does interop with go-ipfs**, in fact:

- js-ipfs can use a go-ipfs generated repo just fine
- js-ipfs can talk with a go-ipfs nodes and fetch files

**Comment by richardschneider** [comment]
So the current fix is to edit the `version` file and change the "5" to "6",

**Comment by diasdavid** [comment]
Yes. I believe we have fixed them all now
