### ISSUE TITLE
Possible mistake in documentation in README.md

### ISSUE THREAD

**Issue by jonahweissman** [ipfs/js-ipfs-repo#157]
In README.md, it says:

> repo.open (callback)
>  
> Locks the repo.
> 
> repo.close (callback)
> 
> Unlocks the repo.

I found this really counter-intuitive. I'm guessing that this is a mistake, and `open` unlocks while `close` locks. If not, maybe there could be a brief explanation?

**Comment by diasdavid** [comment]
I see the argument for renaming it to `lock, unlock`. Would you like to submit a PR with improved docs and the new interface?

**Comment by jonahweissman** [comment]
Sure! I'm on it

**Comment by jonahweissman** [comment]
Upon further reflection, I decided that `open` and `close` were pretty appropriate names, as long as they are explained a bit. I made a PR that attempts to clarify.

**Comment by diasdavid** [comment]
Thanks @jonahweissman :)
