### ISSUE TITLE
Allow the repo locker to be passed by configuration

### ISSUE THREAD

**Issue by jacobheun** [ipfs/js-ipfs-repo#161]
Currently the only available lockers are fs and memory. It's currently not possible to set a locker via configuration. Providing support for this would allow new datastores to provide their own locking mechanism.

Perhaps updating the Repo initialization to include a `locker` property would be a good approach:
```
const repo = new Repo({
  locker: require('./my-locker')
})
```
Then when setting `this._locker` internally, it could check for either  this.options.locker, or the `fs|memory` keys in this.options.lock

connects to ipfs/js-datastore-s3#1

**Comment by diasdavid** [comment]
Thanks for bringing this up. I agree there is a good case to make the lock file optional and even avoiding using fs-ext to lock on fs (which causes problems to electron). From my side:

- 👍 on making the lock optional and configurable.
- 👍 on abandoning fs-ext.
