### ISSUE TITLE
Add Lead Maintainer

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-repo#170]
As per ipfs/pm#600, please list yourself as the Lead Maintainer

**Comment by jacobheun** [comment]
@diasdavid https://github.com/ipfs/js-ipfs-repo/pull/166 is open, the review got reverted because the commit lint was failing (I didnt have commit signing on), so I amended it. I can merge that once it's approved.

**Comment by diasdavid** [comment]
thank you! merged
