### ISSUE TITLE
repo.stat reads entire of blockstore into memory

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs-repo#180]
In IPFS repo.stat takes about 5s per call for me. I found that that the entire blockstore is read into memory every time this function is called to get the count and size:

https://github.com/ipfs/js-ipfs-repo/blob/3611043d81f3d5ff2ed36ed1efe3f4889561493e/src/index.js#L301-L317

This needs to be streamed and/or calculated once, cached, and kept up to date.

**Comment by achingbrain** [comment]
This was fixed by #199 Phew!
