### ISSUE TITLE
proper-lockfile errors after sleep

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js-ipfs-repo#188]
1. Start an IPFS daemon
1. Put your computer to sleep for 30s
1. 💥
    ```
    /Users/alan/Code/protocol-labs/js-ipfs/node_modules/proper-lockfile/lib/lockfile.js:181
            onCompromised: (err) => { throw err; },
                                      ^

    Error: Unable to update lock within the stale threshold
        at options.fs.utimes (/Users/alan/Code/protocol-labs/js-ipfs/node_modules/proper-lockfile/lib/lockfile.js:109:21)
        at FSReqWrap.oncomplete (fs.js:141:20)
    ```

**Comment by achingbrain** [comment]
Silly question, but since everything is immutable, why do we need to lock the repo?  There would need to be some inter-process guarding around things like the MFS root hash or the pin sets to prevent simultaneous writes, but for the most part shouldn't it all be append-only?

**Comment by hugomrdias** [comment]
brainstorming this with @satazor (proper-lockfile creator)

**Comment by jacobheun** [comment]
> Silly question, but since everything is immutable, why do we need to lock the repo? There would need to be some inter-process guarding around things like the MFS root hash or the pin sets to prevent simultaneous writes, but for the most part shouldn't it all be append-only?

We had previously looked at making locking optional, but there were concerns about doing that. I think a primary concern would be protecting against multi-tenancy issues, especially if we end up with different versions of go/js. I haven't done much exploration into this though.

> brainstorming this with @satazor (proper-lockfile creator)

@hugomrdias any update on this? Do we need the staleness check? We previously didn't have it and it was only added with proper-lock. Perhaps an intermediary solution would be to do some checking in the `onCompromised` option and refresh the lock if it was a staleness issue. This isn't ideal, but it would at least prevent these staleness issues until we have an appropriate resolution.

**Comment by satazor** [comment]
I had a discussion last week. The issue is that proper-lockfile fails if the time it took to update the lock was greater than the threshold. Now, this doesn't necessarly mean that the lock was compromised but, at the moment, proper-lockfile throws. We have discussed in doing an extra check to prevent it from throwing. That will solve the sleep scenario as well as the one in which the event loop is blocked for quite some time.

**Comment by alanshaw** [comment]
@satazor do you think you'll be able to implement a fix soon? This issue is a big problem for anyone using a JS IPFS daemon with IPFS companion.

**Comment by hugomrdias** [comment]
@satazor will not be able to take this, i will implement the extra check in proper-lockfile

**Comment by nick** [comment]
I'm seeing the sleep issue too. Not sure how to help, though... if someone with more context could provide some pointers I'd be happy to take a look.

**Comment by hugomrdias** [comment]
can you please validate that this PR https://github.com/moxystudio/node-proper-lockfile/pull/74 fixes the problem pls ?

**Comment by alanshaw** [comment]
@hugomrdias would you mind submitting a PR here so I can do the same for js-ipfs?

**Comment by hugomrdias** [comment]
i will once i release proper-lockfile
can link it in js-ipfs and validate the fix? i pushed some more commits to the branch just now

**Comment by jacobheun** [comment]
Should be resolve in `v0.26.3`
