### ISSUE TITLE
lock-memory - won't fail if lock already exists

### ISSUE THREAD

**Issue by AuHau** [ipfs/js-ipfs-repo#194]
While working on the repo migration tool, I have noticed that the implementation of in-memory lock in `lock-memory.js` behaves in bit weird way as it will acquire lock even if there is already lock in place.
It exposes function `locked()`, yet I have not found it used anywhere. But even then I think the correct behavior of any locking functionality should be to fail when there is a lock already present.

I understand that in browser there might not be really concurrent processes, so I am just wondering if that was a design decision or is it a bug?

**Comment by jacobheun** [comment]
I think this is a bug, it should really fail if it already exists. While the use case of that actually being the case should be low, it should still protect against acquiring an already existing lock.

**Comment by AuHau** [comment]
Solved by #200
