### ISSUE TITLE
fix aegir browser cov

### ISSUE THREAD

**Issue by hugomrdias** [ipfs/js-ipfs-repo#294]
some repos from js ipfs hang when generating cov

https://github.com/istanbuljs/v8-to-istanbul/pull/139
https://github.com/hugomrdias/playwright-test/pull/168

**Comment by BigLep** [comment]
@hugomrdias : what are the next steps here?  Was any investigation done?

**Comment by hugomrdias** [comment]
this is already fixed in aegir, it can be closed
