### ISSUE TITLE
Init check fails but version does exist (migrating 9 -> 10)

### ISSUE THREAD

**Issue by valmack** [ipfs/js-ipfs-repo#299]
Hello!

I'm trying to migrate a repo from v9 to v10. It uses s3 as a backend for ipfs-repo.

### Before migration attempt
The repo clearly has **version and config** files.
```
λ cat version 
9
```
<img width="152" alt="image" src="https://user-images.githubusercontent.com/8445610/114022614-f5416f80-983f-11eb-86b1-d6a63011739b.png">

### During migration attempt
The migration is failing and shows the following logs:
```sh
2021-04-08T11:36:27.731Z ipfs:repo opening at: ipfs
--
2021-04-08T11:36:28.234Z ipfs:repo init check
2021-04-08T11:36:28.459Z ipfs:repo acquired repo.lock
2021-04-08T11:36:28.713Z ipfs:repo:version comparing version: 9 and 10
2021-04-08T11:36:29.233Z ipfs:repo migrating to version 10

2021-04-08T11:36:29.787Z ipfs:repo:migrator:repo:init Version entry present: false # <---- WHY??
2021-04-08T11:36:29.787Z ipfs:repo:migrator:repo:init Config entry present: false # <---- WHY??

NotInitializedRepoError: Repo in path ipfs is not initialized!
at Object.getVersion (/ipfs-repo-migrations/src/repo/version.js:22:11)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.migrate (/ipfs-repo-migrations/src/index.js:67:26)
at async IpfsRepo.open (/ipfs-repo/src/index.js:120:11)
at async openRepo (/ipfs-core/src/components/storage.js:88:7)
at async loadRepo (/ipfs-core/src/components/storage.js:60:21)
at async Function.start (/ipfs-core/src/components/storage.js:44:41)
at async Object.create (/ipfs-core/src/components/index.js:208:21)
at async Function.create (/ipfs-daemon.js:65:22) {
code: 'ERR_NOT_INITIALIZED_REPO'
}
```
### After migration attempt
The repo gets 2 new files which seem like they should not be there and version is still on 9
<img width="149" alt="image" src="https://user-images.githubusercontent.com/8445610/114022339-a7c50280-983f-11eb-8775-039bf06269a7.png">

----------

Could the issue be here?
https://github.com/ipfs/js-ipfs-repo/blob/a36e69590603e9dcc2f82c8e09c02bc3d90292ae/src/version.js#L26-L31

**Comment by valmack** [comment]
For context we have updated our dependencies from

```js
// prev versions
"ipfs": "0.52.2",
"ipfs-http-gateway": "^0.3.0",
"ipfs-http-server": "0.3.1",
```

to

```js
// curr versions
"ipfs": "~0.54.2",
"ipfs-http-gateway": "~0.3.2",
"ipfs-http-server": "~0.3.3"
```

**Comment by achingbrain** [comment]
Could you check the config and see if the root datastore is being sharded?  I think what may be happening here is when a repo is first initted the basic structure is created - the blocks dir, version file, etc - without any sharding.  Sharding is applied per-datastore so doesn't need to be applied to the root.

When the repo-migrations tool tries to read the version number it applies whatever datastore options have been passed - if you're using the default [createRepo](https://github.com/ipfs/js-datastore-s3/blob/master/src/s3-repo.js#L48) script bundled with `datastore-s3` it'll try to shard everything which is a bug.

I have [updated the file](https://github.com/ipfs/js-datastore-s3/blob/fix/remove-create-s3-repo/examples/full-s3-repo/create-s3-repo.js) in https://github.com/ipfs/js-datastore-s3/pull/33 to only shard the blockstore and the pinstore as the other datastores should be small enough that sharding isn't necessary, and the root itself should never be sharded.

**Comment by valmack** [comment]
Hey @achingbrain thanks for looking into this. We are creating the repo like so

```js
const repo = configuration.ipfsS3RepoEnabled ? createRepo({
            path: configuration.ipfsPath,
        }, {
            bucket: configuration.awsBucketName,
            accessKeyId: configuration.awsAccessKeyId,
            secretAccessKey: configuration.awsSecretAccessKey,
        }) : configuration.ipfsPath
```

Current config (pre-migration of course) is this
```json
"datastore": {
    "Spec": {
      "type": "mount",
      "mounts": [
        {
          "mountpoint": "/blocks",
          "type": "measure",
          "prefix": "flatfs.datastore",
          "child": {
            "type": "flatfs",
            "path": "blocks",
            "sync": true,
            "shardFunc": "/repo/flatfs/shard/v1/next-to-last/2"
          }
        },
        {
          "mountpoint": "/",
          "type": "measure",
          "prefix": "leveldb.datastore",
          "child": {
            "type": "levelds",
            "path": "datastore",
            "compression": "none"
          }
        }
      ]
    }
  },
```

So my guess is that this **bug** _is_ affecting us.

**Comment by achingbrain** [comment]
Have you managed to perform the migration?  It should be as straightforward as using the (updated) [create-s3-repo.js](https://github.com/ipfs/js-datastore-s3/blob/master/examples/full-s3-repo/create-s3-repo.js) file from `datastore-s3` - it's been moved to the examples folder so you'll need to copy it into your project and ensure you have a version of `ipfs-repo` in your deps that matches the version `ipfs` is using.

The only thing to double check would be [which datastores are sharded](https://github.com/ipfs/js-datastore-s3/blob/master/examples/full-s3-repo/create-s3-repo.js#L61-L82) - if you look in the `blocks`, `datastore`, `keys` and `pins` folders of your s3 bucket they'll be sharded if they are full of very short-named folders, otherwise not.

**Comment by valmack** [comment]
@achingbrain thanks for merging this fix. I'll be testing it within the next couple days as we copy over the create repo code and let you know how it goes.

**Comment by lidel** [comment]
@valmack feel free to reopen if still an issue in  the latest release.
