### ISSUE TITLE
Service Already Present.

### ISSUE THREAD

**Issue by Jan877** [ipfs/js-ipfs-repo#323]
By mistake, I removed Pinata from Settings|IPFS. 
I tried to redownload it, but I got the message "Service Already Present". 
I can't redownload Pinata, nothing happens. 

<img width="960" alt="Service Already Present" src="https://user-images.githubusercontent.com/44270690/124376346-e46d9200-dca6-11eb-8caa-765808511076.png">

**Comment by achingbrain** [comment]
I think you've opened this issue on the wrong repo.  Your problem is likely something to do with Pinata, [go-ipfs](https://github.com/ipfs/go-ipfs) or [ipfs-webui](https://github.com/ipfs/ipfs-webui).
