### ISSUE TITLE
[bug] wrong dependency declaration

### ISSUE THREAD

**Issue by onichandame** [ipfs/js-ipfs-repo#334]
### Problem

Example:

In a [source file](https://github.com/ipfs/js-ipfs-repo/blob/a00ae495ea9a636de6369201d4f7b5787055c36a/src/idstore.js#L5) it requires `it-drain`, but in the [package.json](https://github.com/ipfs/js-ipfs-repo/blob/a00ae495ea9a636de6369201d4f7b5787055c36a/package.json#L62) it is declared as a devDependency, which results in a missing package error.

The same problem exists for `ts-drain` and `ts-first`

### Solution

move `it-drain` and `ts-first` from devDeps to deps

**Comment by achingbrain** [comment]
Thanks for pointing this out - if you've identified a fix, please open a PR 😁

**Comment by onichandame** [comment]
It can be fixed in 2 ways at least. move them to `dependencies` section, or copy them to `peerDependencies` section. Deciding which way is better requires the knowledge of whether they should be required by the apps that use this lib.

```text
# move to dependencies
app -> js-ipfs-repo -> ts-drain/it-drain/ts-first

# copy to peerDependencies
app -> js-ipfs-repo
    -> ts-drain/it-drain/ts-first

**Comment by BigLep** [comment]
Per verbal with @achingbrain , please move this to ``dependencies``.

**Comment by onichandame** [comment]
The master branch already fixed this. `it-drain` has been moved to `dependencies` section and the other 2 have been removed entirely.
