### ISSUE TITLE
IPFS Repo Feature - Implement `datastore-legacy`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-repo#6]
> IPFS nodes store some IPLD objects locally.

Full Information: https://github.com/ipfs/specs/blob/fix-repo/repo/README.md#datastore
Complete Spec: https://github.com/ipfs/specs/blob/fix-repo/repo/README.md

**Comment by diasdavid** [comment]
@jbenet please itemise what is available on the 'datastore-legacy'

**Comment by diasdavid** [comment]
- [ ] We need a levelDB blob store implementation (currently there is only one for IndexDB on the browser, should be similar, but not equal)

**Comment by jbenet** [comment]
Isn't there a levelup blob store? (Taking any leveldown?)

**Comment by jbenet** [comment]
https://github.com/maxogden/abstract-blob-store/issues/19

**Comment by diasdavid** [comment]
this is the `blocks store` which is implemented :)
