### ISSUE TITLE
Update encodings following the changes in go-ipfs

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-repo#67]
Ref 

- https://github.com/ipfs/go-datastore/pull/39
- https://github.com/ipfs/go-datastore/pull/41
- https://github.com/ipfs/go-ipfs/pull/2903

New paths are `/block/${base-32-std-no-padding-encoded-hash}`

**Comment by diasdavid** [comment]
Done on -> https://github.com/ipfs/js-ipfs-repo/pull/76, closing this one, tracking through the PR
