### ISSUE TITLE
IPFS Repo Feature - Implement `logs`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-repo#8]
> A full IPFS node is complex. Many events can happen, and thus some ipfs implementations capture event logs and (optionally) store them for user review or debugging.

Full information: https://github.com/ipfs/specs/blob/fix-repo/repo/README.md#logs
Complete Repo Spec - https://github.com/ipfs/specs/blob/fix-repo/repo/README.md

**Comment by masylum** [comment]
In the specs it reads the following:

> NOTE: go-ipfs no longer stores logs. it only emits them at a given route. This section is kept here in case other implementations may wish to store logs, though it may be removed in the future.

**Comment by diasdavid** [comment]
Thank you @masylum :):)

Closing this one then
