### ISSUE TITLE
Add test-utils

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-repo#82]
Currently the setup and teardown of a repo with pre populated data is copy and pasted over most js-ipfs repos. To fix this add 
- `repo.load('path-to-repo', cb)` which does 
  - in the browser: https://github.com/ipfs/js-ipfs-repo/blob/master/test/browser.js#L24-L48
  - in node: https://github.com/ipfs/js-ipfs-repo/blob/master/test/node.js#L18-L21
- `repo.delete(cb)` which does
  - in the browser: https://github.com/ipfs/js-ipfs-repo/blob/master/test/browser.js#L13-L19
  - in node: https://github.com/ipfs/js-ipfs-repo/blob/master/test/node.js#L25-L28

**Comment by diasdavid** [comment]
What if we make this a separate module `ipfs-repo-utils`? @pgte wanna take a look at this?

**Comment by diasdavid** [comment]
It might be the case that having them here is also fine. I'm just considering adding more code to the bundles. Probably having a `ipfs-repo/src/utils` would do fine :)

**Comment by pgte** [comment]
I think this is badly needed in tests, but I also think we shouldn't add to any browser bundle.
My opinion is that this should be a separate require like a separate repo or, more simply `require('ipfs-repo/utils')`.

I tend to like this last one better (ETOOMANYREPOS)..

**Comment by dignifiedquire** [comment]
agree with @pgte not another repo please, just publish it along side in its own file such that browser bundlers don't pick it up unless you explicitly require it

**Comment by diasdavid** [comment]
@pgte let's do it then :D to the IPFS Repo release train! 🚂

**Comment by achingbrain** [comment]
Closing because the approach now is to not have dependencies of IPFS depend on IPFS, so most of them don't have repos in their tests.
